name: Build Board Images
on: [push]
jobs:
  build-images:
    strategy:
      matrix:
        board_name:
          - raspberrypi4
          - raspberrypi4_64
    continue-on-error: true # allow other boards to continue even if one fails
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Enable ccache
        uses: actions/cache@v3
        with:
          path: ~/.buildroot-ccache
          key: build_cache-${{ matrix.board_name }}-${{ github.sha }}
          restore-keys: |
            build_cache-${{ matrix.board_name }}-
            build_cache-
      - name: generate config
        run: make ${{ matrix.board_name }}-config
      - name: build
        run: make ${{ matrix.board_name }}
      - name: prepare artifacts
        run: mkdir artifacts && mv output/images/**.img* artifacts
      - name: upload generated images
        uses: actions/upload-artifact@v3
        with:
          name: board images
          path: artifacts/
  upload-developer-tools:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare artifacts
        run: mkdir artifacts && mv scripts artifacts
      - name: upload scripts
        uses: actions/upload-artifact@v3
        with:
          name: board images
          path: artifacts/write_image.sh
