name: Build Board Images
on: [push]
jobs:
  build-images:
    strategy:
      matrix:
        board_name:
          - raspberrypi4_64
    continue-on-error: true # allow other boards to continue even if one fails
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Enable ccache
        uses: actions/cache@v3
        with:
          path: ~/.buildroot-ccache
          key: build_cache-${{ matrix.board_name }}-${{ github.sha }}
          restore-keys: build_cache-${{ matrix.board_name }}-
      - name: generate config
        run: make BR2_CCACHE=y ${{ matrix.board_name }}-config
      - name: build
        run: make
      - name: upload generated images
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.board_name }}-images
          path: "*.img*"
